/**
 * Sidebar for product documentation (docs/)
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        description: 'Get up and running with 8Labs in minutes',
      },
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Billing & Plans',
      link: {
        type: 'generated-index',
        description: 'Understand pricing, plans, and billing',
      },
      items: [{type: 'autogenerated', dirName: 'billing-plans'}],
    },
    {
      type: 'category',
      label: 'FAQ',
      link: {
        type: 'generated-index',
        description: 'Frequently asked questions',
      },
      items: [{type: 'autogenerated', dirName: 'faq'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: {
        type: 'generated-index',
        description: 'Common issues and how to resolve them',
      },
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },
  ],
};

export default sidebars;
