/**
 * Sidebar configuration for 8Labs documentation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // Introduction at the top
    'intro',
    
    // All categories in order
    {
      type: 'category',
      label: 'Cloud 8Labs 101',
      link: {
        type: 'generated-index',
        description: 'Getting started with Cloud 8Labs services',
      },
      items: [{type: 'autogenerated', dirName: 'cloudlabs-101'}],
    },
    {
      type: 'category',
      label: 'Caddy',
      link: {
        type: 'generated-index',
        description: 'How to use, configure and deploy Caddy as a web server',
      },
      items: [{type: 'autogenerated', dirName: 'caddy-101'}],
    },
    {
      type: 'category',
      label: 'VMware',
      link: {
        type: 'generated-index',
        description: 'VMware ESXi administration and management',
      },
      items: [{type: 'autogenerated', dirName: 'VMware'}],
    },
    {
      type: 'category',
      label: 'Proxmox',
      link: {
        type: 'generated-index',
        description: 'Proxmox VE tutorials and troubleshooting',
      },
      items: [{type: 'autogenerated', dirName: 'proxmox'}],
    },
    {
      type: 'category',
      label: 'XCP-ng',
      link: {
        type: 'generated-index',
        description: 'XCP-ng deployment, hardening, and VMware coexistence',
      },
      items: [{type: 'autogenerated', dirName: 'XCP-ng'}],
    },
    {
      type: 'category',
      label: 'Rocky Linux',
      link: {
        type: 'generated-index',
        description: 'Enterprise Linux configuration and best practices',
      },
      items: [{type: 'autogenerated', dirName: 'rocky-linux'}],
    },
    {
      type: 'category',
      label: 'WireGuard',
      link: {
        type: 'generated-index',
        description: 'WireGuard VPN setup and configuration',
      },
      items: [{type: 'autogenerated', dirName: 'wireguard'}],
    },
    {
      type: 'category',
      label: 'Git',
      link: {
        type: 'generated-index',
        description: 'Git workflows and best practices',
      },
      items: [{type: 'autogenerated', dirName: 'git'}],
    },
    {
      type: 'category',
      label: 'Coolify',
      link: {
        type: 'generated-index',
        description: 'Coolify deployment platform guides and tutorials',
      },
      items: [{type: 'autogenerated', dirName: 'coolify'}],
    },
  ],
};

export default sidebars;
